In [2]:
from bs4 import BeautifulSoup # this module helps in web scrapping.
import requests  # this module helps us to download a web page

## Beautiful Soup Objects

Beautiful Soup is a Python library for pulling data out of HTML and XML files, we will focus on HTML files. This is accomplished by representing the HTML as a set of objects with methods used to parse the HTML. We can navigate the HTML as a tree and/or filter out what we are looking for.

In [3]:
%%html
<!DOCTYPE html>
<html>
<head>
<title>Page Title</title>
</head>
<body>
<h3><b id='boldest'>Lebron James</b></h3>
<p> Salary: $ 92,000,000 </p>
<h3> Stephen Curry</h3>
<p> Salary: $85,000, 000 </p>
<h3> Kevin Durant </h3>
<p> Salary: $73,200, 000</p>
</body>
</html>

**Note** : Make sure you load into one line itself

In [5]:
# Storing the above webpage as a string
html="<!DOCTYPE html><html><head><title>Page Title</title></head><body><h3><b id='boldest'>Lebron James</b></h3><p> Salary: $ 92,000,000 </p><h3> Stephen Curry</h3><p> Salary: $85,000, 000 </p><h3> Kevin Durant </h3><p> Salary: $73,200, 000</p></body></html>"

First, the document is converted to Unicode, (similar to ASCII), and HTML entities are converted to Unicode characters. Beautiful Soup transforms a complex HTML document into a complex tree of Python objects. The BeautifulSoup object can create other types of objects. In this lab, we will cover BeautifulSoup and Tag objects that for the purposes of this lab are identical, and NavigableString objects.

In [6]:
soup=BeautifulSoup(html,"html.parser")

In [7]:
print(soup)

<!DOCTYPE html>
<html><head><title>Page Title</title></head><body><h3><b id="boldest">Lebron James</b></h3><p> Salary: $ 92,000,000 </p><h3> Stephen Curry</h3><p> Salary: $85,000, 000 </p><h3> Kevin Durant </h3><p> Salary: $73,200, 000</p></body></html>

We can use the method prettify() to display the HTML in the nested structure:

In [8]:
print(soup.prettify())

<!DOCTYPE html>
<html>
 <head>
  <title>
   Page Title
  </title>
 </head>
 <body>
  <h3>
   <b id="boldest">
    Lebron James
   </b>
  </h3>
  <p>
   Salary: $ 92,000,000
  </p>
  <h3>
   Stephen Curry
  </h3>
  <p>
   Salary: $85,000, 000
  </p>
  <h3>
   Kevin Durant
  </h3>
  <p>
   Salary: $73,200, 000
  </p>
 </body>
</html>

## Tags
Let's say we want the title of the page and the name of the top paid player we can use the Tag. The Tag object corresponds to an HTML tag in the original document, for example, the tag title.

In [9]:
tag_object=soup.title
tag_object

we can see the tag type bs4.element.Tag

In [10]:
type(tag_object)

bs4.element.Tag

If there is more than one Tag with the same name, the first element with that Tag name is called, this corresponds to the most paid player:

In [11]:
tag_object_1=soup.h3
tag_object_1

## Children, Parents, and Siblings
As stated above the Tag object is a tree of objects we can access the child of the tag or navigate down the branch as follows:

In [16]:
tag_child =tag_object.b
tag_child

In [17]:
parent_tag=tag_child.parent
parent_tag

AttributeError: 'NoneType' object has no attribute 'parent'

In [18]:
tag_object.parent

In [20]:
print(tag_object.next_sibling)

None

## HTML Attributes
If the tag has attributes, the tag id="boldest" has an attribute id whose value is boldest. You can access a tagâ€™s attributes by treating the tag like a dictionary:

In [ ]:
tag_child.attrs

## Navigable String
A string corresponds to a bit of text or content within a tag. Beautiful Soup uses the NavigableString class to contain this text. In our HTML we can obtain the name of the first player by extracting the sting of the Tag object tag_child as follows:

In [ ]:
tag_string=tag_child.string

In [ ]:
type(tag_string)

In [ ]:
unicode_string = str(tag_string)
unicode_string

## Filter
Filters allow you to find complex patterns, the simplest filter is a string. In this section we will pass a string to a different filter method and Beautiful Soup will perform a match against that exact string. Consider the following HTML of rocket launchs:

In [25]:
%%html
<table>
  <tr>
    <td id='flight' >Flight No</td>
    <td>Launch site</td> 
    <td>Payload mass</td>
   </tr>
  <tr> 
    <td>1</td>
    <td><a href='https://en.wikipedia.org/wiki/Florida'>Florida</a></td>
    <td>300 kg</td>
  </tr>
  <tr>
    <td>2</td>
    <td><a href='https://en.wikipedia.org/wiki/Texas'>Texas</a></td>
    <td>94 kg</td>
  </tr>
  <tr>
    <td>3</td>
    <td><a href='https://en.wikipedia.org/wiki/Florida'>Florida<a> </td>
    <td>80 kg</td>
  </tr>
</table>

In [26]:
table="<table><tr><td id='flight'>Flight No</td><td>Launch site</td> <td>Payload mass</td></tr><tr> <td>1</td><td><a href='https://en.wikipedia.org/wiki/Florida'>Florida<a></td><td>300 kg</td></tr><tr><td>2</td><td><a href='https://en.wikipedia.org/wiki/Texas'>Texas</a></td><td>94 kg</td></tr><tr><td>3</td><td><a href='https://en.wikipedia.org/wiki/Florida'>Florida<a> </td><td>80 kg</td></tr></table>"

In [27]:
table_bs=BeautifulSoup(table,"html.parser")

## find All
The find_all() method looks through a tagâ€™s descendants and retrieves all descendants that match your filters.

The Method signature for find_all(name, attrs, recursive, string, limit, **kwargs)

## NameÂ¶
When we set the name parameter to a tag name, the method will extract all the tags with that name and its children.

In [28]:
table_rows=table_bs.find_all('tr')
table_rows

[<tr><td id="flight">Flight No</td><td>Launch site</td> <td>Payload mass</td></tr>,
 <tr> <td>1</td><td><a href="https://en.wikipedia.org/wiki/Florida">Florida<a></a></a></td><td>300 kg</td></tr>,
 <tr><td>2</td><td><a href="https://en.wikipedia.org/wiki/Texas">Texas</a></td><td>94 kg</td></tr>,
 <tr><td>3</td><td><a href="https://en.wikipedia.org/wiki/Florida">Florida<a> </a></a></td><td>80 kg</td></tr>]

The result is a Python Iterable just like a list, each element is a tag object:

In [29]:
first_row =table_rows[0]
first_row

In [30]:
print(type(first_row))

<class 'bs4.element.Tag'>

In [31]:
first_row.td

If we iterate through the list, each element corresponds to a row in the table:

In [32]:
for i,row in enumerate(table_rows):
    print("row",i,"is",row)

row 0 is <tr><td id="flight">Flight No</td><td>Launch site</td> <td>Payload mass</td></tr>
row 1 is <tr> <td>1</td><td><a href="https://en.wikipedia.org/wiki/Florida">Florida<a></a></a></td><td>300 kg</td></tr>
row 2 is <tr><td>2</td><td><a href="https://en.wikipedia.org/wiki/Texas">Texas</a></td><td>94 kg</td></tr>
row 3 is <tr><td>3</td><td><a href="https://en.wikipedia.org/wiki/Florida">Florida<a> </a></a></td><td>80 kg</td></tr>

As row is a cell object, we can apply the method find_all to it and extract table cells in the object cells using the tag td, this is all the children with the name td. The result is a list, each element corresponds to a cell and is a Tag object, we can iterate through this list as well. We can extract the content using the string attribute.

In [34]:
for i,row in enumerate(table_rows):
    print("row",i,"is",row)
    cells=row.find_all('td')
    for j,cells in enumerate(cells):
        print("column",j,"is",cells)

row 0 is <tr><td id="flight">Flight No</td><td>Launch site</td> <td>Payload mass</td></tr>
column 0 is <td id="flight">Flight No</td>
column 1 is <td>Launch site</td>
column 2 is <td>Payload mass</td>
row 1 is <tr> <td>1</td><td><a href="https://en.wikipedia.org/wiki/Florida">Florida<a></a></a></td><td>300 kg</td></tr>
column 0 is <td>1</td>
column 1 is <td><a href="https://en.wikipedia.org/wiki/Florida">Florida<a></a></a></td>
column 2 is <td>300 kg</td>
row 2 is <tr><td>2</td><td><a href="https://en.wikipedia.org/wiki/Texas">Texas</a></td><td>94 kg</td></tr>
column 0 is <td>2</td>
column 1 is <td><a href="https://en.wikipedia.org/wiki/Texas">Texas</a></td>
column 2 is <td>94 kg</td>
row 3 is <tr><td>3</td><td><a href="https://en.wikipedia.org/wiki/Florida">Florida<a> </a></a></td><td>80 kg</td></tr>
column 0 is <td>3</td>
column 1 is <td><a href="https://en.wikipedia.org/wiki/Florida">Florida<a> </a></a></td>
column 2 is <td>80 kg</td>

If we use a list we can match against any item in that list.

In [35]:
list_input=table_bs .find_all(name=["tr", "td"])
list_input

[<tr><td id="flight">Flight No</td><td>Launch site</td> <td>Payload mass</td></tr>,
 <td id="flight">Flight No</td>,
 <td>Launch site</td>,
 <td>Payload mass</td>,
 <tr> <td>1</td><td><a href="https://en.wikipedia.org/wiki/Florida">Florida<a></a></a></td><td>300 kg</td></tr>,
 <td>1</td>,
 <td><a href="https://en.wikipedia.org/wiki/Florida">Florida<a></a></a></td>,
 <td>300 kg</td>,
 <tr><td>2</td><td><a href="https://en.wikipedia.org/wiki/Texas">Texas</a></td><td>94 kg</td></tr>,
 <td>2</td>,
 <td><a href="https://en.wikipedia.org/wiki/Texas">Texas</a></td>,
 <td>94 kg</td>,
 <tr><td>3</td><td><a href="https://en.wikipedia.org/wiki/Florida">Florida<a> </a></a></td><td>80 kg</td></tr>,
 <td>3</td>,
 <td><a href="https://en.wikipedia.org/wiki/Florida">Florida<a> </a></a></td>,
 <td>80 kg</td>]

# Downloading And Scraping The Contents Of A Web Page

In [36]:
url = "http://www.ibm.com"

We use *get* to download the contents of the webpage in text format and store in a variable called *data*:

In [37]:
data=requests.get(url).text

We create a BeautifulSoup object using the BeautifulSoup constructor

In [38]:
soup=BeautifulSoup(data,"html.parser")

In [41]:
# Scrape all links
for link in soup.find_all('a',href=True): # in html anchor/link is represented by the tag <a>
    print(link.get('href'))

https://www.ibm.com/resources/the-data-differentiator/scale-ai?lnk=hpenls1
https://www.ibm.com/watsonx?lnk=hpenls2
https://www.ibm.com/events/reg/flow/ibm/mknmeomb/landing/page/landing?lnk=hpenca1
//mediacenter.ibm.com/id/1_t4tolges
//mediacenter.ibm.com/id/1_t4tolges
//mediacenter.ibm.com/id/1_t4tolges
https://www.ibm.com/in-en/data-fabric?lnk=hpencm1
//mediacenter.ibm.com/id/1_ohfv4i6v
//mediacenter.ibm.com/id/1_ohfv4i6v
//mediacenter.ibm.com/id/1_ohfv4i6v
https://www.ibm.com/in-en/sustainability?lnk=hpencm2
//mediacenter.ibm.com/id/1_4f1czavh
//mediacenter.ibm.com/id/1_4f1czavh
//mediacenter.ibm.com/id/1_4f1czavh
https://www.ibm.com/consulting/?lnk=hpencm3
#tab_3171780
#tab_3171784
#tab_3171788
#tab_3171792
#tab_3171796
#tab_3171800
https://www.ibm.com/consulting/?lnk=hpenco1
https://www.ibm.com/consulting/strategy/?lnk=hpenco2
https://www.ibm.com/consulting/ibmix?lnk=flathl
https://www.ibm.com/consulting/technology/?lnk=hpenco4
https://www.ibm.com/services/operations-consulting?lnk=flathl
/strategic-partnerships?lnk=hpenco6
https://www.ibm.com/case-studies/enento-group?lnk=hpencs1
https://www.ibm.com/products/instana/resources/india-demo?lnk=hpencs2
https://www.ibm.com/careers/in-en/?lnk=flatitem
https://www.ibm.com/careers/in-en/?lnk=flatitem
https://research.ibm.com/
https://research.ibm.com/
https://www.ibm.com/in-en/impact/responsibility
https://www.ibm.com/in-en/impact/responsibility
https://www.ibm.com/threat-detection-response?lnk=hpenf2
/in-en/about
https://www.ibm.com/subscribe?hpenab1=
#

## Scraping all image tags

In [42]:
for link in soup.find_all('img'):
    print(link.get('src'))

//1.cms.s81c.com/sites/default/files/2023-04-05/CS_The_Modernize_Banking_Question_V1_30_mobile-frame-04-30_drupal.jpg
//1.cms.s81c.com/sites/default/files/2023-04-05/CS_The_Sustainability_Building_Question_30_mobile-07-00_drupal.jpg
//1.cms.s81c.com/sites/default/files/2023-04-05/CS_the_transform_masters_question_30_mobile_frame00_drupal_0.jpg
//1.cms.s81c.com/sites/default/files/2023-05-07/pi-1906698.xl_.jpg
//1.cms.s81c.com/sites/default/files/2023-05-07/ebsf02532.xl_.jpg
//1.cms.s81c.com/sites/default/files/2023-05-07/_l7a6081.xl_.jpg
//1.cms.s81c.com/sites/default/files/2022-11-16/XLG%20-%20IBM%20Consulting%20-%20Technology.jpg
//1.cms.s81c.com/sites/default/files/2022-11-16/XLG%20-%20IBM%20Consulting%20-%20Operations.jpg
//1.cms.s81c.com/sites/default/files/2022-11-16/XLG%20-%20IBM%20Consulting%20-%20Partners.jpg
//1.cms.s81c.com/sites/default/files/2022-11-16/XLG%20-%20Inside%20IBM%20-%20IBM%20Careers.jpg
//1.cms.s81c.com/sites/default/files/2022-11-16/XLG%20-%20Inside%20IBM%20-%20Research%20Labs.jpg
//1.cms.s81c.com/sites/default/files/2022-11-16/XLG%20-%20Inside%20IBM%20-%20Corporate%20Social%20Responsibility.jpg

## Scraping data from tBLES

In [43]:
#The below url contains an html table with data about colors and color codes.
url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DA0321EN-SkillsNetwork/labs/datasets/HTMLColorCodes.html"

Before proceeding to scrape a web site, you need to examine the contents, and the way data is organized on the website. Open the above url in your browser and check how many rows and columns are there in the color table.

In [44]:
# get the contents of the webpage in text format and store in a variable called data
data  = requests.get(url).text

In [45]:
soup=BeautifulSoup(data,"html.parser")

In [49]:
table=soup.find('table')

In [50]:
#Get all rows from the table
for row in table.find_all('tr'): # in html table row is represented by the tag <tr>
    # Get all columns in each row.
    cols = row.find_all('td') # in html a column is represented by the tag <td>
    color_name = cols[2].string # store the value in column 3 as color_name
    color_code = cols[3].string # store the value in column 4 as color_code
    print("{}--->{}".format(color_name,color_code))

Color Name--->None
lightsalmon--->#FFA07A
salmon--->#FA8072
darksalmon--->#E9967A
lightcoral--->#F08080
coral--->#FF7F50
tomato--->#FF6347
orangered--->#FF4500
gold--->#FFD700
orange--->#FFA500
darkorange--->#FF8C00
lightyellow--->#FFFFE0
lemonchiffon--->#FFFACD
papayawhip--->#FFEFD5
moccasin--->#FFE4B5
peachpuff--->#FFDAB9
palegoldenrod--->#EEE8AA
khaki--->#F0E68C
darkkhaki--->#BDB76B
yellow--->#FFFF00
lawngreen--->#7CFC00
chartreuse--->#7FFF00
limegreen--->#32CD32
lime--->#00FF00
forestgreen--->#228B22
green--->#008000
powderblue--->#B0E0E6
lightblue--->#ADD8E6
lightskyblue--->#87CEFA
skyblue--->#87CEEB
deepskyblue--->#00BFFF
lightsteelblue--->#B0C4DE
dodgerblue--->#1E90FF

## Scrape data from HTML tables into a DataFrame using BeautifulSoup and Pandas

In [51]:
import pandas as pd

In [52]:
#The below url contains html tables with data about world population.
url = "https://en.wikipedia.org/wiki/World_population"

Before proceeding to scrape a web site, you need to examine the contents, and the way data is organized on the website. Open the above url in your browser and check the tables on the webpage

In [53]:
data=requests.get(url).text

In [54]:
soup=BeautifulSoup(data,"html.parser")

In [56]:
tables=soup.find_all('table')

In [57]:
# we can see how many tables were found by checking the length of the tables list
len(tables)

29

Assume that we are looking for the 10 most densly populated countries table, we can look through the tables list and find the right one we are look for based on the data in each table or we can search for the table name if it is in the table but this option might not always work.

In [63]:
for index,table in enumerate(tables):
    if("region" in str(table)):
        table_index=index
    #if("richest countries" in str(table)):
       # table_index_1=index   
print(table_index)

23

In [69]:
print(tables[23].prettify())

<table class="nowraplinks hlist mw-collapsible autocollapse navbox-inner" style="border-spacing:0;background:transparent;color:inherit">
 <tbody>
  <tr>
   <th class="navbox-title" colspan="2" scope="col">
    <link href="mw-data:TemplateStyles:r1129693374" rel="mw-deduplicated-inline-style"/>
    <link href="mw-data:TemplateStyles:r1063604349" rel="mw-deduplicated-inline-style"/>
    <div class="navbar plainlinks hlist navbar-mini">
     <ul>
      <li class="nv-view">
       <a href="/wiki/Template:Lists_of_countries_by_population_statistics" title="Template:Lists of countries by population statistics">
        <abbr style=";;background:none transparent;border:none;box-shadow:none;padding:0;" title="View this template">
         v
        </abbr>
       </a>
      </li>
      <li class="nv-talk">
       <a href="/wiki/Template_talk:Lists_of_countries_by_population_statistics" title="Template talk:Lists of countries by population statistics">
        <abbr style=";;background:none transparent;border:none;box-shadow:none;padding:0;" title="Discuss this template">
         t
        </abbr>
       </a>
      </li>
      <li class="nv-edit">
       <a class="external text" href="https://en.wikipedia.org/w/index.php?title=Template:Lists_of_countries_by_population_statistics&amp;action=edit">
        <abbr style=";;background:none transparent;border:none;box-shadow:none;padding:0;" title="Edit this template">
         e
        </abbr>
       </a>
      </li>
     </ul>
    </div>
    <div id="Lists_of_countries_by_population_statistics" style="font-size:114%;margin:0 4em">
     <a href="/wiki/Lists_of_sovereign_states_and_dependent_territories" title="Lists of sovereign states and dependent territories">
      Lists of countries
     </a>
     by
     <a href="/wiki/Demographic_statistics" title="Demographic statistics">
      population statistics
     </a>
    </div>
   </th>
  </tr>
  <tr>
   <th class="navbox-group" scope="row" style="width:1%">
    <a class="mw-selflink selflink">
     Global
    </a>
   </th>
   <td class="navbox-list-with-group navbox-list navbox-odd" style="width:100%;padding:0">
    <div style="padding:0 0.25em">
     <ul>
      <li>
       <a href="/wiki/List_of_countries_and_dependencies_by_population" title="List of countries and dependencies by population">
        Current population
       </a>
       <ul>
        <li>
         <a href="/wiki/List_of_countries_by_population_(United_Nations)" title="List of countries by population (United Nations)">
          United Nations
         </a>
        </li>
       </ul>
      </li>
      <li>
       <a href="/wiki/Demographics_of_the_world" title="Demographics of the world">
        Demographics of the world
       </a>
      </li>
     </ul>
    </div>
   </td>
  </tr>
  <tr>
   <th class="navbox-group" scope="row" style="width:1%">
    <a href="/wiki/List_of_continents_and_continental_subregions_by_population" title="List of continents and continental subregions by population">
     Continents/subregions
    </a>
   </th>
   <td class="navbox-list-with-group navbox-list navbox-even" style="width:100%;padding:0">
    <div style="padding:0 0.25em">
     <ul>
      <li>
       <a href="/wiki/List_of_African_countries_by_population" title="List of African countries by population">
        Africa
       </a>
      </li>
      <li>
       <a href="/wiki/Demographics_of_Antarctica" title="Demographics of Antarctica">
        Antarctica
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_Asian_countries_by_population" title="List of Asian countries by population">
        Asia
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_European_countries_by_population" title="List of European countries by population">
        Europe
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_North_American_countries_by_population" title="List of North American countries by population">
        North America
       </a>
       <ul>
        <li>
         <a href="/wiki/List_of_Caribbean_countries_by_population" title="List of Caribbean countries by population">
          Caribbean
         </a>
        </li>
       </ul>
      </li>
      <li>
       <a href="/wiki/List_of_Oceanian_countries_by_population" title="List of Oceanian countries by population">
        Oceania
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_South_American_countries_by_population" title="List of South American countries by population">
        South America
       </a>
      </li>
     </ul>
    </div>
   </td>
  </tr>
  <tr>
   <th class="navbox-group" scope="row" style="width:1%">
    Intercontinental
   </th>
   <td class="navbox-list-with-group navbox-list navbox-odd" style="width:100%;padding:0">
    <div style="padding:0 0.25em">
     <ul>
      <li>
       <a href="/wiki/List_of_countries_in_the_Americas_by_population" title="List of countries in the Americas by population">
        Americas
       </a>
      </li>
      <li>
       <a class="mw-redirect" href="/wiki/List_of_Arab_countries_by_population" title="List of Arab countries by population">
        Arab world
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_member_states_of_the_Commonwealth_of_Nations_by_population" title="List of member states of the Commonwealth of Nations by population">
        Commonwealth of Nations
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_Eurasian_countries_by_population" title="List of Eurasian countries by population">
        Eurasia
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_European_Union_member_states_by_population" title="List of European Union member states by population">
        European Union
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_islands_by_population" title="List of islands by population">
        Islands
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_Latin_American_countries_by_population" title="List of Latin American countries by population">
        Latin America
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_Middle_Eastern_countries_by_population" title="List of Middle Eastern countries by population">
        Middle East
       </a>
      </li>
     </ul>
    </div>
   </td>
  </tr>
  <tr>
   <th class="navbox-group" scope="row" style="width:1%">
    Cities/urban areas
   </th>
   <td class="navbox-list-with-group navbox-list navbox-even" style="width:100%;padding:0">
    <div style="padding:0 0.25em">
     <ul>
      <li>
       <a href="/wiki/List_of_largest_cities" title="List of largest cities">
        World cities
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_national_capitals_by_population" title="List of national capitals by population">
        National capitals
       </a>
      </li>
      <li>
       <a href="/wiki/Megacity" title="Megacity">
        Megacities
       </a>
      </li>
      <li>
       <a href="/wiki/Megalopolis" title="Megalopolis">
        Megalopolises
       </a>
      </li>
     </ul>
    </div>
   </td>
  </tr>
  <tr>
   <th class="navbox-group" scope="row" style="width:1%">
    Past and future
   </th>
   <td class="navbox-list-with-group navbox-list navbox-odd" style="width:100%;padding:0">
    <div style="padding:0 0.25em">
     <ul>
      <li>
       <a href="/wiki/List_of_countries_by_past_and_projected_future_population" title="List of countries by past and projected future population">
        Past and future population
       </a>
      </li>
      <li>
       <a class="mw-redirect" href="/wiki/World_population_estimates" title="World population estimates">
        World population estimates
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_states_by_population_in_1_CE" title="List of states by population in 1 CE">
        1
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_countries_by_population_in_1000" title="List of countries by population in 1000">
        1000
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_countries_by_population_in_1500" title="List of countries by population in 1500">
        1500
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_countries_by_population_in_1600" title="List of countries by population in 1600">
        1600
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_countries_by_population_in_1700" title="List of countries by population in 1700">
        1700
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_countries_by_population_in_1800" title="List of countries by population in 1800">
        1800
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_countries_by_population_in_1900" title="List of countries by population in 1900">
        1900
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_countries_by_population_in_1939" title="List of countries by population in 1939">
        1939
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_countries_by_population_in_1989" title="List of countries by population in 1989">
        1989
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_countries_by_population_in_2000" title="List of countries by population in 2000">
        2000
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_countries_by_population_in_2005" title="List of countries by population in 2005">
        2005
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_countries_by_population_in_2010" title="List of countries by population in 2010">
        2010
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_countries_by_population_in_2015" title="List of countries by population in 2015">
        2015
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_population_milestones_by_country" title="List of population milestones by country">
        Population milestones
       </a>
      </li>
     </ul>
    </div>
   </td>
  </tr>
  <tr>
   <th class="navbox-group" scope="row" style="width:1%">
    <a href="/wiki/Population_density" title="Population density">
     Population density
    </a>
   </th>
   <td class="navbox-list-with-group navbox-list navbox-even" style="width:100%;padding:0">
    <div style="padding:0 0.25em">
     <ul>
      <li>
       <a href="/wiki/List_of_countries_and_dependencies_by_population_density" title="List of countries and dependencies by population density">
        Current density
       </a>
      </li>
      <li>
       <a class="mw-redirect" href="/wiki/Past_and_future_population_density_by_country" title="Past and future population density by country">
        Past and future population density
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_countries_by_real_population_density_based_on_food_growing_capacity" title="List of countries by real population density based on food growing capacity">
        Current real density based on food growing capacity
       </a>
      </li>
     </ul>
    </div>
   </td>
  </tr>
  <tr>
   <th class="navbox-group" scope="row" style="width:1%">
    Growth indicators
   </th>
   <td class="navbox-list-with-group navbox-list navbox-odd" style="width:100%;padding:0">
    <div style="padding:0 0.25em">
     <ul>
      <li>
       <a href="/wiki/List_of_countries_by_population_growth_rate" title="List of countries by population growth rate">
        Population growth rate
       </a>
      </li>
      <li>
       <a class="mw-redirect" href="/wiki/List_of_countries_by_natural_increase" title="List of countries by natural increase">
        Natural increase
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_countries_by_net_reproduction_rate" title="List of countries by net reproduction rate">
        Net reproduction rate
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_countries_by_number_of_births" title="List of countries by number of births">
        Number of births
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_countries_by_number_of_deaths" title="List of countries by number of deaths">
        Number of deaths
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_sovereign_states_and_dependent_territories_by_birth_rate" title="List of sovereign states and dependent territories by birth rate">
        Birth rate
       </a>
      </li>
      <li>
       <a class="mw-redirect" href="/wiki/List_of_countries_by_mortality_rate" title="List of countries by mortality rate">
        Mortality rate
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_sovereign_states_and_dependencies_by_total_fertility_rate" title="List of sovereign states and dependencies by total fertility rate">
        Fertility rate
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_countries_by_past_fertility_rate" title="List of countries by past fertility rate">
        Past fertility rate
       </a>
      </li>
     </ul>
    </div>
   </td>
  </tr>
  <tr>
   <th class="navbox-group" scope="row" style="width:1%">
    <a href="/wiki/Life_expectancy" title="Life expectancy">
     Life expectancy
    </a>
   </th>
   <td class="navbox-list-with-group navbox-list navbox-even" style="width:100%;padding:0">
    <div style="padding:0 0.25em">
     <ul>
      <li>
       <a href="/wiki/List_of_countries_by_life_expectancy" title="List of countries by life expectancy">
        world
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_African_countries_by_life_expectancy" title="List of African countries by life expectancy">
        Africa
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_Asian_countries_by_life_expectancy" title="List of Asian countries by life expectancy">
        Asia
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_European_countries_by_life_expectancy" title="List of European countries by life expectancy">
        Europe
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_North_American_countries_by_life_expectancy" title="List of North American countries by life expectancy">
        North America
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_Oceanian_countries_by_life_expectancy" title="List of Oceanian countries by life expectancy">
        Oceania
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_South_American_countries_by_life_expectancy" title="List of South American countries by life expectancy">
        South America
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_world_regions_by_life_expectancy" title="List of world regions by life expectancy">
        world regions
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_countries_by_past_life_expectancy" title="List of countries by past life expectancy">
        past life expectancy
       </a>
      </li>
     </ul>
    </div>
   </td>
  </tr>
  <tr>
   <th class="navbox-group" scope="row" style="width:1%">
    Other
    <a href="/wiki/Demography" title="Demography">
     demographics
    </a>
   </th>
   <td class="navbox-list-with-group navbox-list navbox-odd" style="width:100%;padding:0">
    <div style="padding:0 0.25em">
     <ul>
      <li>
       <a href="/wiki/List_of_countries_by_mean_age_at_childbearing" title="List of countries by mean age at childbearing">
        Age at childbearing
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_countries_by_age_at_first_marriage" title="List of countries by age at first marriage">
        Age at first marriage
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_countries_by_age_structure" title="List of countries by age structure">
        Age structure
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_countries_by_dependency_ratio" title="List of countries by dependency ratio">
        Dependency ratio
       </a>
      </li>
      <li>
       <a href="/wiki/Divorce_demography" title="Divorce demography">
        Divorce rate
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_countries_ranked_by_ethnic_and_cultural_diversity_level" title="List of countries ranked by ethnic and cultural diversity level">
        Ethnic and cultural diversity level
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_sovereign_states_and_dependent_territories_by_immigrant_population" title="List of sovereign states and dependent territories by immigrant population">
        Immigrant population
       </a>
      </li>
      <li>
       <a href="/wiki/Linguistic_diversity_index" title="Linguistic diversity index">
        Linguistic diversity
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_countries_by_median_age" title="List of countries by median age">
        Median age
       </a>
      </li>
      <li>
       <a class="mw-redirect" href="/wiki/List_of_countries_by_net_migration_rate" title="List of countries by net migration rate">
        Net migration rate
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_countries_by_number_of_households" title="List of countries by number of households">
        Number of households
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_religious_populations" title="List of religious populations">
        Religion
       </a>
       /
       <a href="/wiki/List_of_countries_by_irreligion" title="List of countries by irreligion">
        Irreligion
       </a>
      </li>
      <li>
       <a class="mw-redirect" href="/wiki/List_of_countries_by_sex_ratio" title="List of countries by sex ratio">
        Sex ratio
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_countries_by_urban_population" title="List of countries by urban population">
        Urban population
       </a>
      </li>
      <li>
       <a class="mw-redirect" href="/wiki/Urbanization_by_country" title="Urbanization by country">
        Urbanization
       </a>
      </li>
     </ul>
    </div>
   </td>
  </tr>
  <tr>
   <th class="navbox-group" scope="row" style="width:1%">
    <a href="/wiki/Health" title="Health">
     Health
    </a>
   </th>
   <td class="navbox-list-with-group navbox-list navbox-even" style="width:100%;padding:0">
    <div style="padding:0 0.25em">
     <ul>
      <li>
       <a href="/wiki/List_of_countries_by_antidepressant_consumption" title="List of countries by antidepressant consumption">
        Antidepressant consumption
       </a>
      </li>
      <li>
       <a href="/wiki/Stockpiling_antiviral_medications_for_pandemic_influenza" title="Stockpiling antiviral medications for pandemic influenza">
        Antiviral medications for pandemic influenza
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_countries_by_HIV/AIDS_adult_prevalence_rate" title="List of countries by HIV/AIDS adult prevalence rate">
        HIV/AIDS adult prevalence rate
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_countries_by_infant_and_under-five_mortality_rates" title="List of countries by infant and under-five mortality rates">
        Infant and under-five mortality rates
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_countries_by_maternal_mortality_ratio" title="List of countries by maternal mortality ratio">
        Maternal mortality rate
       </a>
      </li>
      <li>
       <a href="/wiki/List_of_countries_by_obesity_rate" title="List of countries by obesity rate">
        Obesity rate
       </a>
      </li>
      <li>
       <a class="mw-redirect" href="/wiki/List_of_countries_by_percentage_of_population_suffering_from_undernourishment" title="List of countries by percentage of population suffering from undernourishment">
        Percentage suffering from undernourishment
       </a>
      </li>
      <li>

### Converting the above code to a df

In [83]:
population_data = pd.DataFrame(columns=["Rank", "Country", "Population", "Area", "Density"])

for row in tables[7].tbody.find_all("tr"):
    col = row.find_all("td")
    if (col != []):
        rank = col[0].text
        country = col[1].text
        population = col[2].text.strip()
        area = col[3].text.strip()
        density = col[4].text.strip()
        population_data = population_data.append({"Rank":rank, "Country":country, "Population":population, "Area":area, "Density":density}, ignore_index=True)

population_data

C:\Users\91812\AppData\Local\Temp\ipykernel_848\4194156454.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  population_data = population_data.append({"Rank":rank, "Country":country, "Population":population, "Area":area, "Density":density}, ignore_index=True)
C:\Users\91812\AppData\Local\Temp\ipykernel_848\4194156454.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  population_data = population_data.append({"Rank":rank, "Country":country, "Population":population, "Area":area, "Density":density}, ignore_index=True)
C:\Users\91812\AppData\Local\Temp\ipykernel_848\4194156454.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  population_data = population_data.append({"Rank":rank, "Country":country, "Population":population, "Area":area, "Density":density}, ignore_index=True)
C:\Users\91812\AppData\Local\Temp\ipykernel_848\4194156454.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  population_data = population_data.append({"Rank":rank, "Country":country, "Population":population, "Area":area, "Density":density}, ignore_index=True)
C:\Users\91812\AppData\Local\Temp\ipykernel_848\4194156454.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  population_data = population_data.append({"Rank":rank, "Country":country, "Population":population, "Area":area, "Density":density}, ignore_index=True)
C:\Users\91812\AppData\Local\Temp\ipykernel_848\4194156454.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  population_data = population_data.append({"Rank":rank, "Country":country, "Population":population, "Area":area, "Density":density}, ignore_index=True)
C:\Users\91812\AppData\Local\Temp\ipykernel_848\4194156454.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  population_data = population_data.append({"Rank":rank, "Country":country, "Population":population, "Area":area, "Density":density}, ignore_index=True)
C:\Users\91812\AppData\Local\Temp\ipykernel_848\4194156454.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  population_data = population_data.append({"Rank":rank, "Country":country, "Population":population, "Area":area, "Density":density}, ignore_index=True)
C:\Users\91812\AppData\Local\Temp\ipykernel_848\4194156454.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  population_data = population_data.append({"Rank":rank, "Country":country, "Population":population, "Area":area, "Density":density}, ignore_index=True)
C:\Users\91812\AppData\Local\Temp\ipykernel_848\4194156454.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  population_data = population_data.append({"Rank":rank, "Country":country, "Population":population, "Area":area, "Density":density}, ignore_index=True)

  Rank                Country     Population       Area Density
0    1             Â Singapore      5,921,231        719   8,235
1    2            Â Bangladesh    165,650,475    148,460   1,116
2    3  \nÂ Palestine[103]\n\n      5,223,000      6,025     867
3    4                Â Taiwan     23,580,712     35,980     655
4    5           Â South Korea     51,844,834     99,720     520
5    6               Â Lebanon      5,296,814     10,400     509
6    7                Â Rwanda     13,173,730     26,338     500
7    8               Â Burundi     12,696,478     27,830     456
8    9                 Â India  1,389,637,446  3,287,263     423
9   10           Â Netherlands     17,400,824     41,543     419

In [84]:
for row in tables[3].tbody.find_all("tr"):
    col = row.find_all("td")
    if len(col) >= 5:
        region = col[0].text
        density = col[1].text
        Population = col[2].text.strip()
        Most_Populous_Country = col[3].text.strip()
        Most_Prosperous_Country = col[4].text.strip()
        region_popln_data = region_popln_data.append({"Region":region, "Density":density, "Population":Population, "Popln[Most]":Most_Populous_Country, "Prosperity[most]":Most_Prosperous_Country}, ignore_index=True)
region_popln_data

C:\Users\91812\AppData\Local\Temp\ipykernel_848\2844755257.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  region_popln_data = region_popln_data.append({"Region":region, "Density":density, "Population":Population, "Popln[Most]":Most_Populous_Country, "Prosperity[most]":Most_Prosperous_Country}, ignore_index=True)
C:\Users\91812\AppData\Local\Temp\ipykernel_848\2844755257.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  region_popln_data = region_popln_data.append({"Region":region, "Density":density, "Population":Population, "Popln[Most]":Most_Populous_Country, "Prosperity[most]":Most_Prosperous_Country}, ignore_index=True)
C:\Users\91812\AppData\Local\Temp\ipykernel_848\2844755257.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  region_popln_data = region_popln_data.append({"Region":region, "Density":density, "Population":Population, "Popln[Most]":Most_Populous_Country, "Prosperity[most]":Most_Prosperous_Country}, ignore_index=True)
C:\Users\91812\AppData\Local\Temp\ipykernel_848\2844755257.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  region_popln_data = region_popln_data.append({"Region":region, "Density":density, "Population":Population, "Popln[Most]":Most_Populous_Country, "Prosperity[most]":Most_Prosperous_Country}, ignore_index=True)
C:\Users\91812\AppData\Local\Temp\ipykernel_848\2844755257.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  region_popln_data = region_popln_data.append({"Region":region, "Density":density, "Population":Population, "Popln[Most]":Most_Populous_Country, "Prosperity[most]":Most_Prosperous_Country}, ignore_index=True)
C:\Users\91812\AppData\Local\Temp\ipykernel_848\2844755257.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  region_popln_data = region_popln_data.append({"Region":region, "Density":density, "Population":Population, "Popln[Most]":Most_Populous_Country, "Prosperity[most]":Most_Prosperous_Country}, ignore_index=True)
C:\Users\91812\AppData\Local\Temp\ipykernel_848\2844755257.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  region_popln_data = region_popln_data.append({"Region":region, "Density":density, "Population":Population, "Popln[Most]":Most_Populous_Country, "Prosperity[most]":Most_Prosperous_Country}, ignore_index=True)

,Rank,Country,Population,Area,Density,Region,Popln[Most],Prosperity[most]
0,NaN,NaN,"4,641",NaN,104.1\n,Asia\n,"1,418,459,382 â€“ Â India","13,515,000 â€“ Tokyo Metropolis(37,400,000 â€“ G..."
1,NaN,NaN,"1,340",NaN,44.4\n,Africa\n,"0,211,401,000 â€“ Â Nigeria","09,500,000 â€“ Cairo(20,076,000 â€“ Greater Cairo)"
2,NaN,NaN,747,NaN,73.4\n,Europe\n,"0,146,171,000 â€“ Â Russia, approx. 110Â million i...","13,200,000 â€“ Moscow(20,004,000 â€“ Moscow metr..."
3,NaN,NaN,653,NaN,24.1\n,Latin America\n,"0,214,103,000 â€“ Â Brazil","12,252,000 â€“ SÃ£o Paulo City(21,650,000 â€“ SÃ£o..."
4,NaN,NaN,368,NaN,14.9\n,Northern America[note 1]\n,"0,332,909,000 â€“ Â United States","08,804,000 â€“ New York City(23,582,649 â€“ New ..."
5,NaN,NaN,42,NaN,5\n,Oceania\n,"0,025,917,000 â€“ Â Australia","05,367,000 â€“ Sydney"
6,NaN,NaN,0.004[89],NaN,~0\n,Antarctica\n,N/A[note 2],"00,001,258 â€“ McMurdo Station"

## Scrape data from HTML tables into a DataFrame using BeautifulSoup and read_html

Using the same `url`, `data`, `soup`, and `tables` object as in the last section we can use the `read_html` function to create a DataFrame.

Remember the table we need is located in `tables[table_index]`

We can now use the `pandas` function `read_html` and give it the string version of the table as well as the `flavor` which is the parsing engine `bs4`.

In [91]:
pd.read_html(str(tables[3]), flavor='bs4')

[                     Region Density (inhabitants/km2) Population (millions)  \
 0                      Asia                     104.1                  4641
 1                    Africa                      44.4                  1340
 2                    Europe                      73.4                   747
 3             Latin America                      24.1                   653
 4  Northern America[note 1]                      14.9                   368
 5                   Oceania                         5                    42
 6                Antarctica                        ~0             0.004[89]

                                Most populous country  \
 0                              1,418,459,382 â€“ India
 1                            0,211,401,000 â€“ Nigeria
 2  0,146,171,000 â€“ Russia, approx. 110Â million in...
 3                             0,214,103,000 â€“ Brazil
 4                      0,332,909,000 â€“ United States
 5                          0,025,917,000 â€“ Australia
 6                                        N/A[note 2]

               Most populous city (metropolitan area)
 0  13,515,000 â€“ Tokyo Metropolis (37,400,000 â€“ Gr...
 1    09,500,000 â€“ Cairo (20,076,000 â€“ Greater Cairo)
 2  13,200,000 â€“ Moscow (20,004,000 â€“ Moscow metro...
 3  12,252,000 â€“ SÃ£o Paulo City (21,650,000 â€“ SÃ£o ...
 4  08,804,000 â€“ New York City (23,582,649 â€“ New Y...
 5                                05,367,000 â€“ Sydney
 6                       00,001,258 â€“ McMurdo Station  ]

In [93]:
population_data_read_html = pd.read_html(str(tables[5]), flavor='bs4')[0]

population_data_read_html.head()

,#,Most populous countries,2000,2015,2030[A],Graphs are temporarily unavailable due to technical issues.
,Graphs are temporarily unavailable due to technical issues.,Unnamed: 1_level_1,Unnamed: 2_level_1,Unnamed: 3_level_1,Unnamed: 4_level_1,Unnamed: 5_level_1
,Graphs are temporarily unavailable due to technical issues.,Unnamed: 1_level_2,Unnamed: 2_level_2,Unnamed: 3_level_2,Unnamed: 4_level_2,Unnamed: 5_level_2
,Graphs are temporarily unavailable due to technical issues.,Unnamed: 1_level_3,Unnamed: 2_level_3,Unnamed: 3_level_3,Unnamed: 4_level_3,Unnamed: 5_level_3
,Graphs are temporarily unavailable due to technical issues.,Unnamed: 1_level_4,Unnamed: 2_level_4,Unnamed: 3_level_4,Unnamed: 4_level_4,Unnamed: 5_level_4
,Graphs are temporarily unavailable due to technical issues.,Unnamed: 1_level_5,Unnamed: 2_level_5,Unnamed: 3_level_5,Unnamed: 4_level_5,Unnamed: 5_level_5
,Graphs are temporarily unavailable due to technical issues.,Unnamed: 1_level_6,Unnamed: 2_level_6,Unnamed: 3_level_6,Unnamed: 4_level_6,Unnamed: 5_level_6
,Graphs are temporarily unavailable due to technical issues.,Unnamed: 1_level_7,Unnamed: 2_level_7,Unnamed: 3_level_7,Unnamed: 4_level_7,Unnamed: 5_level_7
,Graphs are temporarily unavailable due to technical issues.,Unnamed: 1_level_8,Unnamed: 2_level_8,Unnamed: 3_level_8,Unnamed: 4_level_8,Unnamed: 5_level_8
,Graphs are temporarily unavailable due to technical issues.,Unnamed: 1_level_9,Unnamed: 2_level_9,Unnamed: 3_level_9,Unnamed: 4_level_9,Unnamed: 5_level_9
,Graphs are temporarily unavailable due to technical issues.,Unnamed: 1_level_10,Unnamed: 2_level_10,Unnamed: 3_level_10,Unnamed: 4_level_10,Unnamed: 5_level_10
,Graphs are temporarily unavailable due to technical issues.,Unnamed: 1_level_11,Unnamed: 2_level_11,Unnamed: 3_level_11,Unnamed: 4_level_11,Unnamed: 5_level_11
0,NaN,Graphs are temporarily unavailable due to tech...,NaN,NaN,NaN,NaN
1,1,China[B],1270,1376,1416,NaN
2,2,India,1053,1311,1528,NaN
3,3,United States,283,322,356,NaN
4,4,Indonesia,212,258,295,NaN

## Scrape data from HTML tables into a DataFrame using read_html
We can also use the read_html function to directly get DataFrames from a url.

In [94]:
df=pd.read_html(url,flavor='bs4')

In [96]:
len(df)

26

In [98]:
df[3]

,Region,Density (inhabitants/km2),Population (millions),Most populous country,Most populous city (metropolitan area)
0,Asia,104.1,4641,"1,418,459,382 â€“ India","13,515,000 â€“ Tokyo Metropolis (37,400,000 â€“ Gr..."
1,Africa,44.4,1340,"0,211,401,000 â€“ Nigeria","09,500,000 â€“ Cairo (20,076,000 â€“ Greater Cairo)"
2,Europe,73.4,747,"0,146,171,000 â€“ Russia, approx. 110Â million in...","13,200,000 â€“ Moscow (20,004,000 â€“ Moscow metro..."
3,Latin America,24.1,653,"0,214,103,000 â€“ Brazil","12,252,000 â€“ SÃ£o Paulo City (21,650,000 â€“ SÃ£o ..."
4,Northern America[note 1],14.9,368,"0,332,909,000 â€“ United States","08,804,000 â€“ New York City (23,582,649 â€“ New Y..."
5,Oceania,5,42,"0,025,917,000 â€“ Australia","05,367,000 â€“ Sydney"
6,Antarctica,~0,0.004[89],N/A[note 2],"00,001,258 â€“ McMurdo Station"

We can also use the match parameter to select the specific table we want. If the table contains a string matching the text it will be read.

In [99]:
pd.read_html(url,match='population growth',flavor='bs4')[0]

    Year  Population Yearly growth           Density (pop/km2)  \
    Year  Population             %    Number Density (pop/km2)
0   1951  2584034261         1.88%  47603112                17
1   1952  2630861562         1.81%  46827301                18
2   1953  2677608960         1.78%  46747398                18
3   1954  2724846741         1.76%  47237781                18
4   1955  2773019936         1.77%  48173195                19
..   ...         ...           ...       ...               ...
65  2016  7464022000         1.14%  84225000                50
66  2017  7547859000         1.12%  83837000                51
67  2018  7631091000         1.10%  83232000                51
68  2019  7713468000         1.08%  82377000                52
69  2020  7795000000         1.05%  81331000                52

   Urban population
             Number    %
0         775067697  30%
1         799282533  30%
2         824289989  31%
3         850179106  31%
4         877008842  32%
..              ...  ...
65       4060653000  54%
66       4140189000  55%
67       4219817000  55%
68       4299439000  56%
69       4378900000  56%

[70 rows x 7 columns]